#!/usr/bin/bash

# Notes: just doing a small prototype

declare -g directive

function helpDoc {
	cat <<EOF
Usage:
  iofm [OPTS]
  STDIN | iofm [OPTS]

Synopsis:
  iofm is a file manager that operates on commands provided via stdin and writes the results to stdout.

Description:
  iofm manages files using simple syntax to execute file system operations one at a time or in batches.
  The output of iofm is valid input to iofm with the intent that interactions with iofm take place utilizing a text editor such as vim.

  TODO fill out the rest of the description.
Syntax:
  ./directory:                      denotes the parent directory of the following section
  nodeName                          denotes file or directory node under the current directory
  | content                         denotes an informational line or comment. Will be removed from
                                    output if reprocessed by iofm
  (!d) directive                    Enable directive
  (!g) c                            mixes in the contents of all files after this marker
  (c) fileName                      mixes the contents of the file in the output generated by iofm 
                                    placed directly under the node in the output
  (h) n fileName                    mixes in the n number of lines of content at the beginning of the file
                                    into the output generated by iofm placed directly under the node in
                                    the output
  (t) n fileName                    mixes in the n number of lines of content at the end of the file
                                    into the output generated by iofm placed directly under the node in
                                    the output
  (r) n m fileName                  mixes in the range of n to m lines of content into the output
                                    generated by iofm placed directly under the node in the output
  (to) fileName                     touches a file in the current context denoted by the previous
                                    './directory:'
  (cp) sourceFile destFile          copies the source file from the current context to the provided 
                                    destination file
  (cpr) sourceDir destDir           copies the source directory from the current context to the provided
                                    destionation dir
  (n) nodeName newNodeName          renames a file or directory in the current context denoted by the 
                                    previous './directory:'
  (mv) sourceNode destNode          
  (mk) dirName                      creates a directory under the current context denoted by the 
                                    previous './directory:'
  (d) fileName                      deletes a file under the current context denoted by the 
                                    previous './directory:'
  (dr) fileName                     deletes a directory under the current context denoted by the
                                    previous './directory:'
EOF
}

function processTokens {
	# TODO read using readline
	# lazy detection if line starts with a ./ then its a parent directory.
	# The format of the output tokens will be [context: $folder] (action) args...
	local currentContext
	local pipeIt
	while IFS=$'\n' read -r line; do
		if [[ -z "$pipeIt" && "$line" =~ \(\!g\)\ c ]]; then
			pipeIt=true
			echo "|> $line"
			continue
		fi
		if [[ -z "$directive" && "$line" =~ ^\(\!d\)\ (.*)$ ]]; then
			#echo "| encountered directive: $line"
			directive="${BASH_REMATCH[1]}"
			echo "|> $line"
			continue
		else
			:
			#echo "| directive already declared: $directive"
		fi
		# If line starts with (action) then interpret arguments
		if [[ "$line" =~ ^[\|]\ (.*)$ ]]; then
			if [[ -n "$directive" && "$directive" == 'comments=keep' ]]; then
				echo "$line"
			fi
		elif [[ "$line" =~ ^([.].*)[:]$ ]]; then
			currentContext="${BASH_REMATCH[1]}"
			echo "$line"
		elif [[ "$line" =~ ^[\(](.*)[\)]\ (.*)$ ]]; then
			echo "[context: $currentContext] (${BASH_REMATCH[1]}) ${BASH_REMATCH[2]}"
		elif [[ "$line" =~ ^[.].*[:]$ ]]; then
			echo "$line"
		else
			if [[ -n "$pipeIt" ]]; then
				echo "[context: $currentContext] (c) $line"
			else
				echo "$line"
			fi
		fi
	done
}

function commentOutput {
	while IFS=$'\n' read -r line; do
		echo "| $line"
	done
}

function doAction {
	local arr=("$@")
	local context="${arr[0]}"
	local action="${arr[1]}"
	local args="${arr[@]:2}"
	# TODO need to add error handling.
	local errorMsg
	case "$action" in
	c)
		echo "$args"
		if [[ -f "$context/$args" ]]; then
			commentOutput < <(cat -n "$context/$args")
		elif [[ -d "$context/$args" ]]; then
			# echo "| $args is a directory" >&2
			:
		else
			# echo "| $context/$args doesn't exist" >&2
			:
		fi

		;;
	h)
		local headArgs=($args)
		echo "${headArgs[1]}"
		commentOutput < <(head -n "${headArgs[0]}" "$context/${headArgs[1]}")
		;;
	t)
		local tailArgs=($args)
		echo "${tailArgs[1]}"
		commentOutput < <(tail -n "${tailArgs[0]}" "$context/${tailArgs[1]}")
		;;
	r)
		local rangeArgs=($args)
		echo "${rangeArgs[2]}"
		commentOutput < <(cat -n "$context/${rangeArgs[2]}" | head -n "${rangeArgs[1]}" | tail -n $((${rangeArgs[1]} - ${rangeArgs[0]})))
		;;
	to)
		touch "$context/$args"
		echo "$args"
		;;
	cp)
		echo "| copied $args"
		local copyArgs=($args)
		if [[ -f "$context/${copyArgs[0]}" ]]; then
			# TODO need to add logic to check if target has '/' or not to determine where the file is going in regards to the project.
			cp "$context/${copyArgs[0]}" "${copyArgs[1]}"
		elif [[ -d "$context/${copyArgs[0]}" ]]; then
			echo "| Arg 0 '${copyArgs[0]}' is a directory, use the cpr command to copy"
		else
			echo "| File '${copyArgs[0]}' doesn't exist"
		fi
		;;
	cpr)
		echo "| cpr not yet implemented" >&2
		;;
	n)
		local renameArgs=($args)
		if [[ -f "$context/${renameArgs[0]}" ]]; then
			if [[ -f "$context/${renameArgs[1]}" ]]; then
				echo "| File '${renameArgs[1]}' already exists"
			else
				mv "$context/${renameArgs[0]}" "$context/${renameArgs[1]}"
			fi
		elif [[ -d "$context/${renameArgs[0]}" ]]; then
			if [[ -d "$context/${renameArgs[1]}" ]]; then
				echo "| Dir '${renameArgs[1]}' already exists"
			else
				mv "$context/${renameArgs[0]}" "$context/${renameArgs[1]}"
			fi
		else
			echo "| Source file or dir '${renameArgs[0]}' doesn't exist"
		fi
		;;
	mv)
		# TODO need to update the location output for new file if moved under new parent
		# TODO logic here needs to be a little more complex
		local moveArgs=($args)
		if [[ -f "${moveArgs[0]}" ]]; then
			if [[ -f "${moveArgs[1]}" ]]; then
				echo "| File '${moveArgs[1]}' already exists"
			else
				# TODO need to check if target contains '/' then no change otherwise
				mv "$context/${moveArgs[0]}" "${moveArgs[1]}"
			fi
		elif [[ -d "${moveArgs[0]}" ]]; then
			if [[ -d "${moveArgs[1]}" ]]; then
				echo "| Dir '${moveArgs[1]}' already exists"
			else
				# TODO need to check if target contains '/' then no change otherwise
				mv "$context/${moveArgs[0]}" "${moveArgs[1]}"
			fi
		else
			echo "| File '${moveArgs[0]}' doesn't exist"
		fi
		;;
	mk)
		local mkdirArgs=($args)
		for ((i = 0; i < ${#mkdirArgs[@]}; i++)); do
			if [[ -d "$context/${mkdirArgs[i]}" ]]; then
				echo "| Dir '${mkdirArgs[i]}' already exists"
			else
				mkdir "$context/${mkdirArgs[i]}"
				echo "${mkdirArgs[i]}"
			fi
		done
		;;
	d)
		if [[ -f "$context/$args" ]]; then
			errorMsg="$(rm "$context/$args")"
			echo "| deleted $args"
		else
			echo "| Failed to delete $args"
			commentOutput < <(echo "$errorMsg")
		fi
		;;
	dr)
		if [[ -d "$context/$args" ]]; then
			errorMsg="$(rm -r "$context/$args")"
			echo "| deleted $context/$args"
		else
			echo "| Failed to delete $context/$args"
			commentOutput < <(echo "$errorMsg")
		fi
		;;
		# TODO implement (q) and (a) confirmation prompts
	*)
		echo "| Unknown operation: $action" >&2
		;;
	esac
}

function main {
	if [[ "$1" == "help" ]]; then
		helpDoc
		return 0
	fi
	if [[ -t 0 ]]; then
		ls -R
	else
		while read -r token; do
			lineRead=true
			if [[ "$token" =~ ^[\|][\>]\ (.*)$ ]]; then
				echo "${BASH_REMATCH[1]}"
			elif [[ "$token" =~ ^\[context:\ (.*)]\ [\(](.*)[\)]\ (.*)$ ]]; then
				local context="${BASH_REMATCH[1]}"
				local action="${BASH_REMATCH[2]}"
				local args="${BASH_REMATCH[3]}"
				doAction "$context" "$action" $args
			else
				echo "$token"
			fi
		done < <(processTokens)
		if [[ ! "$lineRead" ]]; then
			ls -R
		fi
	fi
}

main "$@"
