HTTP/2 200 
date: Thu, 14 Aug 2025 00:33:59 GMT
content-type: application/json
cf-ray: 96ec5d2c0f91cef2-EWR
access-control-allow-headers: Content-Type, authorization, User-Agent, Private-Auth-Secret, Discogs-UID
access-control-allow-methods: HEAD,OPTIONS,GET,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Location
cache-control: public, must-revalidate
content-language: en
strict-transport-security: max-age=15552000
vary: Accept-Encoding
x-content-type-options: nosniff
x-discogs-media-type: discogs.v2
x-discogs-ratelimit: 60
x-discogs-ratelimit-remaining: 60
x-discogs-ratelimit-used: 0
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
server: cloudflare
alt-svc: h3=":443"; ma=86400

{
  "pagination": {
    "page": 1,
    "pages": 1,
    "per_page": 50,
    "items": 2,
    "urls": {}
  },
  "results": [
    {
      "country": "Europe",
      "year": "2006",
      "format": [
        "CD",
        "Compilation",
        "Remastered"
      ],
      "label": [
        "Mute",
        "Mute",
        "Mute Records Ltd.",
        "Mute Records Ltd.",
        "Mute Song",
        "Village Recorders",
        "Village Recorders",
        "Greenhouse Studio, London",
        "Hansa Tonstudios",
        "PWL Studios",
        "Worldwide International",
        "Konk Studios",
        "Swanyard Studios",
        "Swanyard Studios",
        "The Garden",
        "Sync City Studios",
        "Worldwide International",
        "Konk Studios",
        "Trident 2",
        "Larrabee North",
        "Steve's Place",
        "Guerilla Studios",
        "Blackwing Studios",
        "Konk Studios",
        "Swanyard Studios",
        "Worldwide International",
        "Unit 3",
        "Studio X, Chicago, Il.",
        "The Exchange",
        "Mediamotion",
        "Mediamotion"
      ],
      "type": "master",
      "genre": [
        "Electronic"
      ],
      "style": [
        "EBM"
      ],
      "id": 12032,
      "barcode": [
        "0 094636 624723 >",
        "LC5834",
        "bel BIEM",
        "0094636624822",
        "0094636624921",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657372@1   010102",
        "IFPI LW03",
        "ifpi AA15",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657372@1   010102",
        "IFPI LW03",
        "ifpi AAH93",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657372@1   010103",
        "IFPI LW03",
        "ifpi AAH34",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657382@2   020104",
        "IFPI LW04",
        "ifpi AAH10",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657382@1   ",
        "IFPI LW03",
        "ifpi 15DE",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657382@1   ",
        "IFPI LW03",
        "ifpi AAH27"
      ],
      "master_id": 12032,
      "master_url": "https://api.discogs.com/masters/12032",
      "uri": "/master/12032-Nitzer-Ebb-Body-Of-Work",
      "catno": "CDMUTEL9",
      "title": "Nitzer Ebb - Body Of Work",
      "thumb": "https://i.discogs.com/oiW-zFkvJMsIgFBoyhgTX38CzvDs04a1wV__IGZmSrs/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwNDky/MS0xMzMzMjAzOTQ4/LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/umCnUGVPr-YjsjL10pTbHpxzPnW93OlHyWreTPU9jnQ/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwNDky/MS0xMzMzMjAzOTQ4/LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/masters/12032",
      "community": {
        "want": 683,
        "have": 1664
      }
    },
    {
      "country": "Europe",
      "year": "2006",
      "format": [
        "CD",
        "Compilation",
        "Remastered"
      ],
      "label": [
        "Mute",
        "Mute",
        "Mute Records Ltd.",
        "Mute Records Ltd.",
        "Mute Song",
        "Village Recorders",
        "Village Recorders",
        "Greenhouse Studio, London",
        "Hansa Tonstudios",
        "PWL Studios",
        "Worldwide International",
        "Konk Studios",
        "Swanyard Studios",
        "Swanyard Studios",
        "The Garden",
        "Sync City Studios",
        "Worldwide International",
        "Konk Studios",
        "Trident 2",
        "Larrabee North",
        "Steve's Place",
        "Guerilla Studios",
        "Blackwing Studios",
        "Konk Studios",
        "Swanyard Studios",
        "Worldwide International",
        "Unit 3",
        "Studio X, Chicago, Il.",
        "The Exchange",
        "Mediamotion",
        "Mediamotion"
      ],
      "type": "release",
      "genre": [
        "Electronic"
      ],
      "style": [
        "EBM"
      ],
      "id": 704921,
      "barcode": [
        "0 094636 624723 >",
        "LC5834",
        "bel BIEM",
        "0094636624822",
        "0094636624921",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657372@1   010102",
        "IFPI LW03",
        "ifpi AA15",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657372@1   010102",
        "IFPI LW03",
        "ifpi AAH93",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657372@1   010103",
        "IFPI LW03",
        "ifpi AAH34",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657382@2   020104",
        "IFPI LW04",
        "ifpi AAH10",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657382@1   ",
        "IFPI LW03",
        "ifpi 15DE",
        "['Mediamotion' logo] WWW.MEDIAMOTION.COM 3657382@1   ",
        "IFPI LW03",
        "ifpi AAH27"
      ],
      "master_id": 12032,
      "master_url": "https://api.discogs.com/masters/12032",
      "uri": "/release/704921-Nitzer-Ebb-Body-Of-Work",
      "catno": "CDMUTEL9",
      "title": "Nitzer Ebb - Body Of Work",
      "thumb": "https://i.discogs.com/oiW-zFkvJMsIgFBoyhgTX38CzvDs04a1wV__IGZmSrs/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwNDky/MS0xMzMzMjAzOTQ4/LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/umCnUGVPr-YjsjL10pTbHpxzPnW93OlHyWreTPU9jnQ/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcwNDky/MS0xMzMzMjAzOTQ4/LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/releases/704921",
      "community": {
        "want": 100,
        "have": 777
      },
      "format_quantity": 2,
      "formats": [
        {
          "name": "CD",
          "qty": "2",
          "descriptions": [
            "Compilation",
            "Remastered"
          ]
        }
      ]
    }
  ]
}
